# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e463e1b6acaa090023dcb0ccb76fff227186aec9b3a7ece39e17978a39152f7fa71cb5e3d14c20b38ffd544df3bacfcbf1ba356c4a90884da5d9416d17c896b

test:
  secret_key_base: 2d6d234dba435a0b20a3532830a430c175ea4a9029e71784dd8e9dc85e95cf3a16c5909a7193f839a78dff8cdcd8744248db154a09c7ac4fbd4634577d97b5d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
